enabled: true
test_types:
  - crlf_injection
  - response_splitting
  - header_pollution
confidence_threshold: 0.8
timeout: 30
max_payloads_per_param: 5
payload_patterns:
  crlf:
    - "\r\nSet-Cookie: injected=true"
    - "\n\rSet-Cookie: injected=true"
    - "%0d%0aSet-Cookie: injected=true"
    - "%0a%0dSet-Cookie: injected=true"
  response_splitting:
    - "\r\n\r\n<script>alert('xss')</script>"
    - "%0d%0a%0d%0a<script>alert('xss')</script>"
test_headers:
  - "User-Agent"
  - "Referer"
  - "X-Forwarded-For" 
  - "X-Real-IP"
  - "Accept-Language"
  - "Accept-Encoding"